language: node_js
branches:
  only:
    - master
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
install:
  - npm install --save-dev
  - npm install -g npm-run
script:
  - npm run build
  - npm-run nyc --reporter=lcov --reporter=text-lcov --report lcovonly npm test
  - npm-run codecov
node_js:
  - "6.1"